# kubeadm-config-c2.yaml
# Configuration file for Cluster 2
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: 1.29.1
clusterName: "local-cluster"
etcd:
  local:
    dataDir: /var/lib/etcd
networking:
  podSubnet: 100.65.0.0/17
  serviceSubnet: 100.65.128.0/17
  dnsDomain: cluster.local

---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
