# kubeadm-config.yaml
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: 1.29.1
clusterName: "local-cluster"
etcd:
  local:
    dataDir: /var/lib/etcd
networking:
  serviceSubnet: 192.168.128.0/17
  podSubnet: 192.168.0.0/17
  dnsDomain: cluster.local

---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
