cluster:
  name: k8s-c1
  id: 1
clustermesh:
  useAPIServer: true
  apiserver:
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    replicas: 2
  config:
    enabled: true
    domain: mesh.cilium.io
    clusters:
    - name: k8s-c2
      address: k8s-c2.mesh.cilium.io
      port: 2379
      ips:
      - 10.104.91.148
      - 10.104.42.62
      tls:
        cert: <encoded cert string in the secret of clustermesh-apiserver-client-cert>
        key: <encoded key string in the secret of clustermesh-apiserver-client-cert>
externalWorkloads:
  enabled: true
envoy:
  enabled: true
apiserver:
ingressController:
  enabled: true
  loadbalancerMode: shared
  service:
    type: NodePort
    insecureNodePort: 30080
    secureNodePort: 30443
