cluster:
  name: k8s-c1
  id: 1
clustermesh:
  config:
    enabled: true
envoy:
  enabled: true
ingressController:
  enabled: true
  loadbalancerMode: shared
  service:
    type: NodePort
    insecureNodePort: 30080
    secureNodePort: 30443
